clone_depth: 1

install:
    # Remove dependencies that prevent us from upgrading to GCC 6.2
    - C:\msys64\usr\bin\bash -lc "pacman -Rs --noconfirm mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-gcc-libgfortran mingw-w64-x86_64-gcc-objc"

    # Update to GCC 6.2 and install dependencies
    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5 mingw-w64-x86_64-libusb mingw-w64-x86_64-boost mingw-w64-x86_64-python3 mingw-w64-x86_64-fftw mingw-w64-x86_64-libzip mingw-w64-x86_64-glibmm mingw-w64-x86_64-ninja"

    # Install pre-compiled libraries
    - appveyor DownloadFile http://swdownloads.analog.com/cse/build/msys64.tar.xz -FileName C:\msys64.tar.xz
    - C:\msys64\usr\bin\bash -lc "cd /c ; tar xJf msys64.tar.xz"

    # Hack: Qt5Qml CMake script throws errors when loading its plugins. So let's just drop those plugins.
    - C:\msys64\usr\bin\bash -lc "rm -f /mingw64/lib/cmake/Qt5Qml/*Factory.cmake"

    # Install Inno Setup
    - choco install InnoSetup

    # Remove the Python stuff that we don't need
    - C:\msys64\usr\bin\bash -lc "find /mingw64/lib/python3.5 -type d -name __pycache__ -exec rm -rf {} + ;"
    - C:\msys64\usr\bin\bash -lc "cd /mingw64/lib/python3.5 ; rm -rf config-3.5m test"

build_script:
    - set PATH=C:\msys64\mingw64\bin;%PATH%
    - C:\msys64\usr\bin\bash -lc "mkdir /c/build ; cd /c/build ; cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DGIT_EXECUTABLE=/c/Program\\ Files/Git/cmd/git.exe -DPKG_CONFIG_EXECUTABLE=/mingw64/bin/pkg-config.exe -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc.exe -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++.exe /c/projects/scopy && ninja"
    - appveyor PushArtifact c:\build\scopy.exe

    # Copy the dependencies
    - mkdir c:\scopy
    - copy c:\build\scopy.exe c:\scopy\
    - c:\msys64\mingw64\bin\windeployqt.exe --dir c:\scopy --release --no-system-d3d-compiler --no-compiler-runtime --no-quick-import c:\build\scopy.exe

    - C:\msys64\usr\bin\bash -lc "tar -C /c/scopy --strip-components=3 -xJf /c/msys64.tar.xz msys64/mingw64/bin"
    - C:\msys64\usr\bin\bash -lc "cd /mingw64/bin ; cp -r libwinpthread-1.dll libgcc_s_seh-1.dll libstdc++-6.dll libboost_{system,filesystem,atomic,program_options,regex,thread}-*.dll libglib-2.0-0.dll libintl-8.dll libiconv-2.dll libpcre-1.dll libpcre16-0.dll libglibmm-2.4-1.dll libgmodule-2.0-0.dll libgobject-2.0-0.dll libffi-6.dll libsigc-2.0-0.dll libfftw3f-3.dll libicu{in,uc,dt}57.dll zlib1.dll libharfbuzz-0.dll libfreetype-6.dll libbz2-1.dll libpng16-16.dll libgraphite2.dll libjpeg-8.dll libsqlite3-0.dll libwebp-6.dll libxml2-2.dll liblzma-5.dll libxslt-1.dll libzip-4.dll libpython3.5m.dll libeay32.dll ssleay32.dll libusb-1.0.dll /mingw64/lib/python3.5 /c/scopy/"

    - 7z a "c:\scopy.zip" c:\scopy
    - appveyor PushArtifact c:\scopy.zip

    # Build the installer
    - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
    - ISCC C:\build\scopy.iss
    - appveyor PushArtifact C:\scopy-setup.exe
